apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-deployments
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          # 1. Manually List Repos (Since SCM Auto-Discovery failed)
          - list:
              elements:
                - url: https://github.com/sarany1947/apps.git
                  branch: main
          # 2. Look for Config File (This part stays the same!)
          - git:
              repoURL: "{{url}}"
              revision: "{{branch}}"
              files:
                - path: ".argocd-config.yaml"
  template:
    metadata:
      name: "{{appName}}"
    spec:
      project: default
      source:
        repoURL: "{{url}}"
        targetRevision: "{{branch}}"
        path: "{{appPath}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{destNamespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
